"""create initial tables

Revision ID: 5398832f8d7c
Revises: 
Create Date: 2025-10-24 22:06:16.975107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5398832f8d7c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('name')
    )
    roles_table = sa.table('roles',
        sa.column('role_id', sa.Integer),
        sa.column('name', sa.String)
    )
    op.bulk_insert(
        roles_table,
        [
            {"role_id": 1, "name": "admin"},
            {"role_id": 2, "name": "editor"},
            {"role_id": 3, "name": "user"},
            {"role_id": 4, "name": "viewer"},
            {"role_id": 5, "name": "guest"},
        ],
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'pending', 'disabled', name='user_status'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('role', sa.Integer, nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index("uq_users_email_lower",
    "users",
    [sa.text("lower(email)")],
    unique=True,
    )
    op.create_table('documents',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.drop_index("uq_users_email_lower", table_name="users")
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
