"""sync models

Revision ID: 94a7237f2135
Revises: 5398832f8d7c
Create Date: 2025-11-03 19:23:15.691547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94a7237f2135'
down_revision: Union[str, Sequence[str], None] = '5398832f8d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_roles_role_id'), 'roles', ['role_id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.INTEGER(),
               server_default='5',
               existing_nullable=False)
    op.drop_index(op.f('uq_users_email_lower'), table_name='users')
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_foreign_key(None, 'users', 'roles', ['role'], ['role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.create_index(op.f('uq_users_email_lower'), 'users', [sa.literal_column('lower(email::text)')], unique=True)
    op.alter_column('users', 'role',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_roles_role_id'), table_name='roles')
    # ### end Alembic commands ###
